name: Auto Endpoint

on:
  push:
    branches:
      - dani
  workflow_dispatch:

jobs:
  edit-urls:
    name: Edit URL Endpoints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Branch
        run: |
          if [ $GITHUB_REF_NAME != "dani" ]; then
            echo "Not $GITHUB_REF_NAME Branch, Exiting..."
            exit 1
          else
            echo "Main Branch Confirmed"
          fi
      - name: Set Env Vars
        run: |
          echo "production_url=theprodurl" >> "$GITHUB_ENV"
          echo "production_key=key1" >> "$GITHUB_ENV"
          echo "development_url=url2" >> "$GITHUB_ENV"
          echo "development_key=key2" >> "$GITHUB_ENV"
      - name: Check Env vars
        run: |
          echo $production_url
          echo $production_key 
          echo $development_url 
          echo $development_key
      - name: Testing sed
        run: |
          sed -i "s/Real/Fake/" main.rs
          cat main.rs
      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated Action"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
