name: Auto Endpoint

on:
  push:
    # branches:
    #   - main
  workflow_dispatch:

jobs:
  edit-urls:
    name: Edit URL Endpoints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Branch
        run: |
          if [ $GITHUB_REF_NAME != "main" ]; then
            echo "Not main Branch, Exiting..."
            exit 1
          else
            echo "Main Branch Confirmed"
          fi
      - name: Set Env Vars
        run: |
          production_url="url1"
          production_key="key1"
          development_url="url2"
          development_key="key2"
      - name: Check Env vars
        run: echo "$production_url $production_key $development_url $development_key"