name: Auto Endpoint

on:
  push:
    # branches:
    #   - main
  workflow_dispatch:

jobs:
  edit-urls:
    name: Edit URL Endpoints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Branch
        run: |
          if [ $GITHUB_REF_NAME != "mainT" ]; then
            echo "Not main Branch, Exiting..."
            exit
          else
            echo "Main Branch Confirmed"
          fi
      - name: Set Env Vars
        run: |
          production_url=theprodurl
          production_key="key1"
          development_url="url2"
          development_key="key2"
          echo $production_url
      - name: Check Env vars
        run: |
          echo $production_url
          echo $production_key 
          echo $development_url 
          echo $development_key