name: Auto Endpoint

on:
  push:
    branches:
      - dani
  workflow_dispatch:

jobs:
  edit-urls:
    name: Edit URL Endpoints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Branch
        run: |
          if [ $GITHUB_REF_NAME != "mainT" ]; then
            echo "Not main Branch, Exiting..."
            exit 1
          else
            echo "Main Branch Confirmed"
          fi
      - name: Set Env Vars
        run: |
          echo "production_url=theprodurl" >> "$GITHUB_ENV"
          echo "production_key=key1" >> "$GITHUB_ENV"
          echo "development_url=url2" >> "$GITHUB_ENV"
          echo "development_key=key2" >> "$GITHUB_ENV"
      - name: Check Env vars
        run: |
          echo $production_url
          echo $production_key 
          echo $development_url 
          echo $development_key
      - name: Testing sed
        run: |
          sed -i "s/Real/Fake/" main.rs
          cat main.rs
      - name: Commit Changes
        run: |
          git config --global user.email "adhueywilan@gmail.com"
          git config --global user.name "DanielHuey"
          git commit -am "Action Commit"
          git push
