name: Rust

on:
  push:
    branches: [ "dani" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Lin
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v4.3.3
      with:
        # Artifact name
        name: rtalk_linux # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/real_talk/real_talk/target/debug/rtalk
  
  build_win:
    name: Win
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - uses: actions/upload-artifact@v4.3.3
        with:
          # Artifact name
          name: rtalk_win # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: 'D:\a\real_talk\real_talk\target\debug\rtalk.exe'
